version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: bbb
    env:
      - CGO_ENABLED=0  
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: bbb
archives:
  - formats: ['zip']
    allow_different_binary_count: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      bbb_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ids:
      - bbb
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}"      
release:
  draft: true
  replace_existing_draft: true
  disable: true